# Generated by Django 4.2.4 on 2023-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='player_stat',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Money'), (2, 'Level'), (3, 'First join time'), (4, 'Last join time'), (5, 'Total hours')], verbose_name='Player stat'),
        ),
    ]
