# Generated by Django 4.2.4 on 2023-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_codes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcode',
            name='hashed_code',
        ),
        migrations.AddField(
            model_name='giftcode',
            name='code',
            field=models.CharField(default=0, max_length=256, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
