# Generated by Django 4.2.4 on 2023-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_join_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_join_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='player',
            name='machine_key',
            field=models.CharField(max_length=256, verbose_name='Machine key'),
        ),
    ]
